version: "3"
services:
    api:
        container_name: "clean_architecture_api"
        build: .
        volumes:
        - .:/go/src/api
        ports:
        - '8000:8080'
        env_file:
        - .env
        depends_on:
        - db
    db:
        container_name: clean-architecture-db
        image: postgres:15.2-alpine
        volumes:
        - dbdata:/var/lib/postgresql/data
        - ./db/init:/docker-entrypoint-initdb.d

        env_file:
        - .env
        tty: true
    adminer:
        container_name: clean-architecture-adminer
        image: adminer:4.7.5
        restart: always
        ports:
        - "8080:8080"
        depends_on:
        - db

volumes:
    dbdata:
        name: go_clean_architecture